_target_: src.models.black_sea.TimeSplineNets

sequence_length: 7
dim: 2

model_cfg:
  encoder:
    _target_: src.models.components.mlp.MLP
    input_dim: 8
    output_dim: 8
  decoder:
    _target_: src.models.components.mlp.MLP
    input_dim: 8
    output_dim: 3
  node_update:
    _target_: src.models.components.mlp.MLP
    input_dim: 9
    output_dim: 8
  edge_update:
    _target_: src.models.components.mlp.MLP
    input_dim: 17
    output_dim: 1