_target_: src.models.graphsplinenets.SpaceSplineNets

model_cfg:
  encoder:
    __target__: src.models.components.mlp.MLP
    input_dim: 3
    output_dim: 8
  decoder:
    __target__: src.models.components.mlp.MLP
    input_dim: 8
    output_dim: 1
  node_update:
    __target__: src.models.components.mlp.MLP
    input_dim: 9
    output_dim: 8
  edge_update:
    __target__: src.models.components.mlp.MLP
    input_dim: 17
    output_dim: 1
